### ISSUE TITLE
basic.py throwing error "An open stream object is being garbage collected; call "stream.close()" explicitly."

### ISSUE THREAD

**Issue by VENTIOR** [voicevox-client/python#15]
[Basic.py](https://github.com/voicevox-client/python/blob/main/examples/basic.py) is throwing me this error in Python 3.10, asyncio 3.4.3. Is this an issue with the client or with asyncio?
**An open stream object is being garbage collected; call "stream.close()" explicitly.**

**Comment by tuna2134** [comment]
Can you show me full error?

**Comment by VENTIOR** [comment]
This is everything it shows me, nothing more nothing less, that's why I haven't been able to find the error. It definitely has something to do with the asyncio library though.

**Comment by tuna2134** [comment]
When I test library I don’t have that error, so I need more survey

**Comment by tuna2134** [comment]
https://github.com/encode/httpx/issues/550
hmm

**Comment by tuna2134** [comment]
https://github.com/encode/httpx/issues/714

**Comment by VENTIOR** [comment]
Seems to be a problem with Python 3.8 - Wait I'm going to look something up.

**Comment by tuna2134** [comment]
Oh, ok

**Comment by VENTIOR** [comment]
Okay, I've set up my Virtual Environment again and it seems that my installation still used asyncio packages from Python 3.8. My mistake...So it should be mentioned that Python >=3.9 should be used.
![image](https://user-images.githubusercontent.com/88195766/226073027-e9f2f1ff-c8af-486e-b6f1-9bf4aa1cbd77.png)

**Comment by tuna2134** [comment]
Ok
