### ISSUE TITLE
Is there a way to change the speed that the text is read at?

### ISSUE THREAD

**Issue by ktesterman007** [voicevox-client/python#27]
Hi, I really like this project, and I'm using it right now to read whatever is on my clipboard when I press a hotkey.  I just wanted to know, is there any way to adjust the speed that the text is read at?  If not, would it be possible to add this as a feature?

Thanks!

**Comment by AbstractUmbra** [comment]
This is possible with the voicevox engine, but it is currently not within the library. I will keep you posted on this, though!

**Comment by tuna2134** [comment]
```py
async with Client(..) as client:
    audio_query = await client.create_audio_query(0, "こんにちは")
    audio_query.speed_scale = 2
    await audio_query.synthesis(0)
```

**Comment by tuna2134** [comment]
Sample code
