### ISSUE TITLE
Help Required for installation

### ISSUE THREAD

**Issue by Nexus-Vediir** [voicevox-client/python#28]
Hey! I'm trying to get VoiceVox to work on my PC for a little python script I'm setting up.
Problem is, I can't find a guide and I'm getting error messages with the stuff I'm trying. 
Whenever I try to install the VoiceVox library `python -m pip install Voicevox`, it'll give me a WinError notifying me that the process was stopped because the setup file was marked as malware. After disabling my anti-virus and attempting to run, it got a decode error. 
```python
C:\Users\main>python -m pip install voicevox
Collecting voicevox
  Using cached voicevox-0.0.6.tar.gz (3.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\main\AppData\Local\Temp\pip-install-dg7h0p8o\voicevox_df1210a9c88c46d5aba617b99b951679\setup.py", line 11, in <module>
          long_description = f.read()
        File "C:\Users\main\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 287: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I have... no clue how to work this. 
I've been hearing stuff about 'docker'...

For greater context, I'm trying to create a script that uses VoiceVox to read back user text. 
Thanks to anyone who could help!

**Comment by AbstractUmbra** [comment]
Hi, you appear to be installing `voicevox` which is not our package.
We maintain `voicevox-client`, a Python library for interacting with a Voicevox server.

Running the server is separate to this repository, but you can obtain this [here](https://voicevox.hiroshiba.jp/)!

There's also [this repository](https://github.com/VOICEVOX/voicevox_engine) if you just wish to run the engine/backend separately. They provide instructions on how to use Docker if you wish to go that route!

**Comment by tuna2134** [comment]
Sorry, When I released first version, I used voicevox name, but official voicevox maintainer said to me, Please change library name, so I changed
