### ISSUE TITLE
Confused between speaker and style.

### ISSUE THREAD

**Issue by alessandrosp** [voicevox-client/python#57]
- The documentation mentions speaker a few times but all the methods only accept style. I believe this is a bug, see for example: https://voicevox-client.tuna2134.jp/#voicevox.Client.create_audio_query
- What's the difference between setting the style when the Client is created vs. when synthetize() is executed?
- What's the correct way to change the speaker?

**Comment by alessandrosp** [comment]
This fork fixed the problems I mentioned above, which makes me believe these are actually bugs: https://github.com/Nakanishi123/voicevox-python

**Comment by tuna2134** [comment]
> * The documentation mentions speaker a few times but all the methods only accept style. I believe this is a bug, see for example: https://voicevox-client.tuna2134.jp/#voicevox.Client.create_audio_query
> * What's the difference between setting the style when the Client is created vs. when synthetize() is executed?
> * What's the correct way to change the speaker?

We are fixing about this. Please wait a moment

**Comment by tuna2134** [comment]
voicevox-engine change speaker to style_id, so I need to change this.

**Comment by tuna2134** [comment]
> * The documentation mentions speaker a few times but all the methods only accept style. I believe this is a bug, see for example: https://voicevox-client.tuna2134.jp/#voicevox.Client.create_audio_query
> * What's the difference between setting the style when the Client is created vs. when synthetize() is executed?
> * What's the correct way to change the speaker?
For example, it is used when you want to read out the pronunciation of Zundamon with the voice of another speaker.

**Comment by tuna2134** [comment]
We fixed
https://github.com/voicevox-client/python/releases/tag/v0.4.0
