### ISSUE TITLE
Programming getting started guide

### ISSUE THREAD

**Issue by IzMike** [voicevox-client/python#7]
Is there a tutorial on getting started coding with this API?
I've tried to install and use it but it always gives me weird errors that I cannot solve. Even the example code is not working for some reason.

**Comment by tuna2134** [comment]
> Is there a tutorial on getting started coding with this API?
> I've tried to install and use it but it always gives me weird errors that I cannot solve. Even the example code is not working for some reason.

Oh
Okay, can you give me error and code?

**Comment by tuna2134** [comment]
hmm, time-out error?

**Comment by tuna2134** [comment]
I think voicevox engine is down

**Comment by IzMike** [comment]
Like, down, down? Or is it a problem on my end?

**Comment by IzMike** [comment]
How did you manage to install it and run it with the example code? What operation system did you use?

**Comment by tuna2134** [comment]
> Like, down, down? Or is it a problem on my end?

Do you run voicevox-engine?

**Comment by tuna2134** [comment]
> How did you manage to install it and run it with the example code? What operation system did you use?

I use docker

**Comment by IzMike** [comment]
Oh, I see. May you help me a little on this one? I'm really lost

**Comment by tuna2134** [comment]
> Oh, I see. May you help me a little on this one? I'm really lost

Ok
Can you come [here](https://discord.gg/FqefJaVq)?

**Comment by IzMike** [comment]
It's not letting me join

**Comment by tuna2134** [comment]
hmm
I see
Do you have docker?

**Comment by IzMike** [comment]
I'm installing it right now. Also, we can chat privately on Discord, I just need your user and tag

**Comment by IzMike** [comment]
> hmm I see Do you have docker?

I've installed it.

**Comment by tuna2134** [comment]
If you have cpu, please run this
```sh
docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
docker run --rm -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest
```

**Comment by tuna2134** [comment]
Or if you have gpu please run this
```
docker pull voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
docker run --rm --gpus all -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:nvidia-ubuntu20.04-latest```

**Comment by IzMike** [comment]
Alright

**Comment by IzMike** [comment]
Do I need to run it in the voicevox directory?

**Comment by IzMike** [comment]
I get this error:
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
upon running: ```docker run --rm --gpus all -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:nvidia-ubuntu20.04-latest```

**Comment by tuna2134** [comment]
Do u have nvida’s gpu?

**Comment by IzMike** [comment]
Yes

**Comment by IzMike** [comment]
Should I install the cpu one instead?

**Comment by tuna2134** [comment]
hmm
```sh
sudo apt-get install nvidia-container-runtime
```
If you have ubuntu, please run this command.

**Comment by IzMike** [comment]
It shows me this
E: Unable to locate package nvidia-container-runtime

**Comment by tuna2134** [comment]
```sh
curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
sudo apt-get update
```
Run this command before that command.

**Comment by IzMike** [comment]
Alright I've managed to run both of them

**Comment by IzMike** [comment]
It gives me this error:
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by IzMike** [comment]
> > It gives me this error:
> > docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
> 
> Hello!
> 
> Is the host computer here a server without a GPU or is it a machine with a GPU?
> 
> I personally had this issue running on my development server since it doesn't have one installed.

I'm using a virtual machine. There is a gpu in my pc, but now that you say it, maybe the virtual machine doesn't recognize it.
Perhaps I should use the cpu version

**Comment by tuna2134** [comment]
> Can't install the cpu version now? That's really weird

Nop

**Comment by tuna2134** [comment]
Is host pc is windows?
If you use windows please use voicevox official app.
Voicevox official app has voicevox-engine too.

**Comment by IzMike** [comment]
I'm running this program on Linux. And I have installed the AppImage file, so I do have Voicevox installed on my machine

**Comment by tuna2134** [comment]
hmm
What is you host pc os?

**Comment by IzMike** [comment]
Linux on a virtual machine

**Comment by AbstractUmbra** [comment]
> Can't install the cpu version now? That's really weird

Sorry could you tell me what the issue with the CPU version is?
I personally run this one in Docker on my hosting solution, seems to work just fine.

**Comment by IzMike** [comment]
Upon running: docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
docker run --rm -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest

it kinda freezes. Is that normal?

**Comment by AbstractUmbra** [comment]
Which part freezes exactly?
The command here downloads and spawns a container, but not interactively or detached. You might want to use `docker run -it ...` to spawn an interactive shell or `docker run -d ...` to run a detached session.

**Comment by IzMike** [comment]
For some reason it's working now. Thank you for your help guys. I really appreciate it!
So now I can just run my script and it'll work?

**Comment by AbstractUmbra** [comment]
Should do! Have fun!

**Comment by IzMike** [comment]
Thank you!

**Comment by IzMike** [comment]
One last question th

**Comment by IzMike** [comment]
One last question though. Is there a way to stop the docker service for the voicevox cpu version?

**Comment by AbstractUmbra** [comment]
You can peruse the running containers with `docker ps`, find the container name or id and then use `docker stop {item}` to stop it.

**Comment by IzMike** [comment]
> @IzMike May I close?

Yes. Thank you.
